---
server:
  logging:
    level:
      org:
        springframework: DEBUG
  port: 8080
  servlet:
    session:
      cookie:
        name: JAVASESSIONID
        max-age: 7200

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bd_bus_tickets_api
    username: pguser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855